spring:

  application:
    name: notice-board

  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/notice-board
    username: sa

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true