CREATE TABLE TBL_MEMBERS (
    MEMBER_ID BIGINT NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    MODIFIED_AT TIMESTAMP(6),
    EMAIL CHARACTER VARYING(30) NOT NULL UNIQUE,
    NAME CHARACTER VARYING(30)
);
