CREATE TABLE TBL_POSTS (
    POST_ID BIGINT NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    MODIFIED_AT TIMESTAMP(6),
    CONTENT CHARACTER VARYING(500),
    STATUS CHARACTER VARYING(255),
    TITLE CHARACTER VARYING(50),
    MEMBER_ID BIGINT,
    FOREIGN KEY (MEMBER_ID) REFERENCES TBL_MEMBERS(MEMBER_ID)
);
